---
name: Main workflow

on:
  - push
  - pull_request

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup NPM
        uses: actions/setup-node@v2
        with:
          node-version: lts/*
      - name: Install node modules
        run: npm install
      - name: Lint markdown files
        run: make lint-markdown
      - name: Lint YAML files
        run: make lint-yaml

  shellcheck:
    name: Shell check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        files:
          - i-doit.sh
          - idoit
          - idoit-backup
          - idoit-hotfix
          - idoit-install
          - idoit-jobs
          - idoit-pwd
          - idoit-restore
          - idoit-support
    steps:
      - name: Lint ${{ matrix.files }}
        uses: ludeeus/action-shellcheck@master
        env:
          SHELLCHECK_OPTS: ${{ matrix.files }}
