---
name: Main workflow

on:
  - push
  - pull_request

jobs:

  lint:
    name: Lint files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Setup NPM
        uses: actions/setup-node@v2
        with:
          node-version: lts/*
      - name: Install node modules
        run: npm install
      - name: Install yamllint
        run: pip install yamllint
      - name: Lint markdown files
        run: npm run test:markdown
      - name: Lint shell scripts
        run: npm run test:shell
      - name: Lint YAML files
        run: npm run test:yaml
      - name: Audit NPM modules
        run: npm audit
